version: '3.5'

services:
  ps_db:
    container_name: 'ps_db'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    image: postgres:15.0-bullseye
    networks:
      - kiwikaf

  redis_db:
    container_name: 'redis_db'
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_PASSWORD=root
      - REDIS_USER=redis
      - REDIS_DATABASES=1
    image: redis/redis-stack:latest
    networks:
      - kiwikaf


  myapp:
    image: tg-bot-trans
    container_name: 'tg-bot-trans'
    ports:
      - "8000:8000"
    build: .
    depends_on:
      - ps_db
      - redis_db
    networks:
      - kiwikaf


networks:
  kiwikaf:
    name: kiwikaf