version: '3.5'

services:
  ps_db:
    container_name: 'ps_db'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    image: postgres:15.0-bullseye
    networks:
      - kiwikaf

  zookeeper-1:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kiwikaf

  kafka-1:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_BASE_CLIENT_BOOTSTRAPSERVERS: kafka-1:29092
      KAFKA_ADVERTISED_HOST_NAME: localhost:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_CLIENT_USERS: 'user'
      KAFKA_CLIENT_PASSWORDS: 'password'
    networks:
      - kiwikaf

  kafka-2:
    image: confluentinc/cp-kafka
    ports:
      - 9093:9092
    depends_on:
      - zookeeper-1
      - kafka-1
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29092,EXTERNAL://localhost:9093
      KAFKA_BASE_CLIENT_BOOTSTRAPSERVERS: kafka-2:29092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_CLIENT_USERS: 'user'
      KAFKA_CLIENT_PASSWORDS: 'password'

    networks:
      - kiwikaf
  kafka-3:
    image: confluentinc/cp-kafka
    ports:
      - 9094:9092
    depends_on:
      - zookeeper-1
      - kafka-1
      - kafka-2
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29092,EXTERNAL://localhost:9094
      KAFKA_BASE_CLIENT_BOOTSTRAPSERVERS: kafka-3:29092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_CLIENT_USERS: 'user'
      KAFKA_CLIENT_PASSWORDS: 'password'

    networks:
      - kiwikaf

  kiwi:
    image: dmwood/kiwi
    ports:
      - "8081:8080"
    depends_on:
      - zookeeper-1
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      KAFKA_BASE_CLIENT_BOOTSTRAPSERVERS: kafka-1:29092,kafka-2:29092,kafka-3:29092
    networks:
      - kiwikaf

networks:
  kiwikaf:
    name: kiwikaf