version: '3.5'

services:
  ps_db:
    container_name: 'ps_db'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
    image: postgres:15.0-bullseye
    networks:
      - kiwikaf

  redis_db:
    container_name: 'redis_db'
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=root
      - REDIS_USER=redis
    image: redis:7.2.3-bookworm
    networks:
      - kiwikaf

networks:
  kiwikaf:
    name: kiwikaf